language: python
python:
  - "2.7"
  - "pypy"
env:
  - DJANGO_VERSION=1.9.6
  - DJANGO_VERSION=1.9.7
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script: python manage.py test
services:
  - redis-server